DEFAULT_CLEARANCE = 0
CORRIDOR_WIDTH = 1

MIN_WATER_LINE = 10
MAX_WATER_LINE = 30

MIN_WALL_BLOCKS = 1
MAX_WALL_BLOCKS = 4

MIN_COVER_CLUSTERS = 10
MAX_COVER_CLUSTERS = 40

MIN_BUSH_PATCHES = 10
MAX_BUSH_PATCHES = 30

MIN_BOXES = 20
MAX_BOXES = 60


MAP_SIZE = 60
if MAP_SIZE%2 != 0:
    raise ValueError("Map Size must be even")