DEFAULT_CLEARANCE = 0
CORRIDOR_WIDTH = 1

MIN_WATER_LINE = 1
MAX_WATER_LINE = 10

MIN_WALL_BLOCKS = 1
MAX_WALL_BLOCKS = 15

MIN_COVER_CLUSTERS = 40
MAX_COVER_CLUSTERS = 80

MIN_BUSH_PATCHES = 30
MAX_BUSH_PATCHES = 54

MIN_BOXES = 20
MAX_BOXES = 60


MAP_SIZE = 60
if MAP_SIZE%2 != 0:
    raise ValueError("Map Size must be even")